/*
 *
 *  Created on: 2023年10月10日
 *      Author: weich
 */

#ifndef LIB_WAYNEPCAP_WAYNEENUMS_HPP_
#define LIB_WAYNEPCAP_WAYNEENUMS_HPP_

namespace wayne {
	namespace PCAP {
		enum blockTypes
		{
			INTERFACE_DESCRIPTION = 1,
			PACKET = 2,
			SIMPLE_PACKET = 3,
			NAME_RESOLUTION = 4,
			INTERFACE_STATISTICS = 5,
			ENHANCED_PACKET = 6,
			IRIG_TIMESTAMP = 7,
			ARINC_429 = 8,
			SYSTEMD_JOURNAL_EXPORT = 9,
			DECRYPTION_SECRETS = 10, 			/*Unsigned HEX: 0000000A*/
			HONE_MACHINE_INFO = 257,			/*Unsigned HEX: 00000101*/
			HONE_PROCESS_INFO = 258, 			/*Unsigned HEX: 00000102*/
			SYSDIG_MACHINE_INFO = 513, 			/*Unsigned HEX: 00000201*/
			SYSDIG_PROCESS_INFO_V1, 			/*Unsigned HEX: 00000202*/
			SYSDIG_FD_LIST, 					/*Unsigned HEX: 00000203*/
			SYSDIG_EVENT, 						/*Unsigned HEX: 00000204*/
			SYSDIG_INTERFACE_LIST, 				/*Unsigned HEX: 00000205*/
			SYSDIG_USER_LIST, 					/*Unsigned HEX: 00000206*/
			SYSDIG_PROCESS_INFO_V2, 			/*Unsigned HEX: 00000207*/
			SYSDIG_EVENT_WITH_FLAGS, 			/*Unsigned HEX: 00000208*/
			SYSDIG_PROCESS_INFO_V3, 			/*Unsigned HEX: 00000209*/
			SYSDIG_PROCESS_INFO_V4 = 528, 		/*Unsigned HEX: 00000210*/
			SYSDIG_PROCESS_INFO_V5, 			/*Unsigned HEX: 00000211*/
			SYSDIG_PROCESS_INFO_V6, 			/*Unsigned HEX: 00000212*/
			SYSDIG_PROCESS_INFO_V7, 			/*Unsigned HEX: 00000213*/
			CUSTOM = 2989, 						/*Unsigned HEX: 00000BAD*/
			CUSTOM_STATIC = 1073744813, 		/*Unsigned HEX: 40000BAD*/
			SECTION_HEADER = 168627466, 		/*Unsigned HEX: 0A0D0D0A*/
		};

		enum structByteLength
		{
			BLOCK_TYPE_LENGTH = 4,
			BLOCK_LENGTH_LENGTH = 4,
			BLOCK_READ_UNIT = 4,

			SHB_BYTE_ORDER_LENGTH = 4,
			SHB_MAJOR_VERSION_LENGTH = 2,
			SHB_MINOR_VERSION_LENGTH = 2,
			SHB_SECTION_LENGTH_LENGTH = 8,

			IDB_LINK_TYPE_LENGTH = 2,
			IDB_RESERVED_LENGTH = 2,
			IDB_SNAP_LENGTH_LENGTH = 2,

			EPB_INTERFACE_ID_LENGTH = 4,
			EPB_TIMESTAMP_FULL_LENGTH = 8,
			EPB_TIMESTAMP_UPPER_LENGTH = 4,
			EPB_TIMESTAMP_LOWER_LENGTH = 4,
			EPB_CAPTURED_PACKET_LENGTH_LENGTH = 4,
			EPB_ORIGINAL_PACKET_LENGTH_LENGTH = 4
		};

		enum structByteDefault
		{
			SHB_MAJOR_VERSION_VALUE = 1,
			SHB_MINOR_VERSION_VALUE = 0,
			SHB_SECTION_LENGTH_VALUE = -1,
			IDB_RESERVED_VALUE = 0,
			IDB_SNAP_LENGTH_VALUE = 262144
		};

		enum optionByteLength
		{
			IF_IPV4ADDR_LENGTH = 8, 			/*4 Byte IP, 4 Byte Mask*/
			IF_IPV6ADDR_LENGTH = 17,			/*16 Byte IP, 1 Byte Mask*/
			IF_MACADDR_LENGTH = 6,
			IF_EUIADDR_LENGTH = 8,
			IF_SPEED_LENGTH = 8,				/*In bits per second*/
			IF_TSRESOL_LENGTH = 1,
			IF_TZONE_LENGTH = 4,
			IF_FCSLEN_LENGTH = 1,
			IF_TSOFFSET_LENGTH = 8,
			IF_TXSPEED_LENGTH = 8,			/*In bits per second*/
			IF_RXSPEED_LENGTH = 8,			/*In bits per second*/
			EPB_FLAGS_LENGTH = 4,
			EPB_DROPCOUNT_LENGTH = 8,
			EPB_PACKETID_LENGTH = 8,
			EPB_QUEUE_LENGTH = 4
		};

		class endianTypesBytes {
			public:
				static const char* ENDIAN_TYPE_SMALL_BYTES;
				static const char* ENDIAN_TYPE_BIG_BYTES;
			/*BIG Unsigned HEX: 1a2b3c4d*/
			/*SMALL Unsigned HEX: 4d3c2b1a*/
		};

		enum endianTypes
		{
			ENDIAN_TYPE_SMALL = 0,
			ENDIAN_TYPE_BIG = 1
		};

		enum optionTypes
		{
			OPT_ENDOFOPT = 0,
			OPT_COMMENT = 1,
			SHB_HARDWARE = 2,
			SHB_OS,
			SHB_USERAPPL,
			IF_NAME = 2,
			IF_DESCRIPTION,
			IF_IPV4ADDR,
			IF_IPV6ADDR,
			IF_MACADDR,
			IF_EUIADDR,
			IF_SPEED,
			IF_TSRESOL,
			IF_TZONE,
			IF_FILTER,
			IF_OS,
			IF_FCSLEN,
			IF_TSOFFSET,
			IF_HARDWARE,
			IF_TXSPEED,
			IF_RXSPEED,
			EPB_FLAGS = 2,
			EPB_HASH,
			EPB_DROPCOUNT,
			EPB_PACKETID,
			EPB_QUEUE,
			EPB_VERDICT,
			OPT_CUSTOM = 2988,
			OPT_CUSTOM_2 = 2989,
			OPT_CUSTOM_3 = 19372,
			OPT_CUSTOM_4 = 19373
		};

		enum linkTypes
		{
			LINKTYPE_NULL,
			LINKTYPE_ETHERNET,
			LINKTYPE_EXP_ETHERNET,
			LINKTYPE_AX25,
			LINKTYPE_PRONET,
			LINKTYPE_CHAOS,
			LINKTYPE_IEEE802_5,
			LINKTYPE_ARCNET_BSD,
			LINKTYPE_SLIP,
			LINKTYPE_PPP,
			LINKTYPE_FDDI,
			LINKTYPE_PPP_HDLC = 50,
			LINKTYPE_PPP_ETHER,
			LINKTYPE_SYMANTEC_FIREWALL = 99,
			LINKTYPE_ATM_RFC1483,
			LINKTYPE_RAW,
			LINKTYPE_SLIP_BSDOS,
			LINKTYPE_PPP_BSDOS,
			LINKTYPE_C_HDLC,
			LINKTYPE_IEEE802_11,
			LINKTYPE_ATM_CLIP,
			LINKTYPE_FRELAY,
			LINKTYPE_LOOP,
			LINKTYPE_ENC,
			LINKTYPE_LANE8023,
			LINKTYPE_HIPPI,
			LINKTYPE_HDLC,
			LINKTYPE_LINUX_SLL,
			LINKTYPE_LTALK,
			LINKTYPE_ECONET,
			LINKTYPE_IPFILTER,
			LINKTYPE_PFLOG,
			LINKTYPE_CISCO_IOS,
			LINKTYPE_IEEE802_11_PRISM,
			LINKTYPE_IEEE802_11_AIRONET,
			LINKTYPE_HHDLC,
			LINKTYPE_IP_OVER_FC,
			LINKTYPE_SUNATM,
			LINKTYPE_RIO,
			LINKTYPE_PCI_EXP,
			LINKTYPE_AURORA,
			LINKTYPE_IEEE802_11_RADIOTAP,
			LINKTYPE_TZSP,
			LINKTYPE_ARCNET_LINUX,
			LINKTYPE_JUNIPER_MLPPP,
			LINKTYPE_JUNIPER_MLFR,
			LINKTYPE_JUNIPER_ES,
			LINKTYPE_JUNIPER_GGSN,
			LINKTYPE_JUNIPER_MFR,
			LINKTYPE_JUNIPER_ATM2,
			LINKTYPE_JUNIPER_SERVICES,
			LINKTYPE_JUNIPER_ATM1,
			LINKTYPE_APPLE_IP_OVER_IEEE1394,
			LINKTYPE_MTP2_WITH_PHDR,
			LINKTYPE_MTP2,
			LINKTYPE_MTP3,
			LINKTYPE_SCCP,
			LINKTYPE_DOCSIS,
			LINKTYPE_LINUX_IRDA,
			LINKTYPE_IBM_SP,
			LINKTYPE_IBM_SN,
			LINKTYPE_RESERVED_01,
			LINKTYPE_RESERVED_02,
			LINKTYPE_RESERVED_03,
			LINKTYPE_RESERVED_04,
			LINKTYPE_RESERVED_05,
			LINKTYPE_RESERVED_06,
			LINKTYPE_RESERVED_07,
			LINKTYPE_RESERVED_08,
			LINKTYPE_RESERVED_09,
			LINKTYPE_RESERVED_10,
			LINKTYPE_RESERVED_11,
			LINKTYPE_RESERVED_12,
			LINKTYPE_RESERVED_13,
			LINKTYPE_RESERVED_14,
			LINKTYPE_RESERVED_15,
			LINKTYPE_RESERVED_16,
			LINKTYPE_IEEE802_11_AVS,
			LINKTYPE_JUNIPER_MONITOR,
			LINKTYPE_BACNET_MS_TP,
			LINKTYPE_PPP_PPPD,
			LINKTYPE_JUNIPER_PPPOE,
			LINKTYPE_JUNIPER_PPPOE_ATM,
			LINKTYPE_GPRS_LLC,
			LINKTYPE_GPF_T,
			LINKTYPE_GPF_F,
			LINKTYPE_GCOM_T1E1,
			LINKTYPE_GCOM_SERIAL,
			LINKTYPE_JUNIPER_PIC_PEER,
			LINKTYPE_ERF_ETH,
			LINKTYPE_ERF_POS,
			LINKTYPE_LINUX_LAPD,
			LINKTYPE_JUNIPER_ETHER,
			LINKTYPE_JUNIPER_PPP,
			LINKTYPE_JUNIPER_FRELAY,
			LINKTYPE_JUNIPER_CHDLC,
			LINKTYPE_MFR,
			LINKTYPE_JUNIPER_VP,
			LINKTYPE_A429,
			LINKTYPE_A653_ICM,
			LINKTYPE_USB_FREEBSD,
			LINKTYPE_BLUETOOTH_HCI_H4,
			LINKTYPE_IEEE802_16_MAC_CPS,
			LINKTYPE_USB_LINUX,
			LINKTYPE_CAN20B,
			LINKTYPE_IEEE802_15_4_LINUX,
			LINKTYPE_PPI,
			LINKTYPE_IEEE802_16_MAC_CPS_RADIO,
			LINKTYPE_JUNIPER_ISM,
			LINKTYPE_IEEE802_15_4_WITHFCS,
			LINKTYPE_SITA,
			LINKTYPE_ERF,
			LINKTYPE_RAIF1,
			LINKTYPE_IPMB_KONTRON,
			LINKTYPE_JUNIPER_ST,
			LINKTYPE_BLUETOOTH_HCI_H4_WITH_PHDR,
			LINKTYPE_AX25_KISS,
			LINKTYPE_LAPD,
			LINKTYPE_PPP_WITH_DIR,
			LINKTYPE_C_HDLC_WITH_DIR,
			LINKTYPE_FRELAY_WITH_DIR,
			LINKTYPE_LAPB_WITH_DIR,
			LINKTYPE_NOTUSED_208,
			LINKTYPE_IPMB_LINUX,
			LINKTYPE_FLEXRAY,
			LINKTYPE_MOST,
			LINKTYPE_LIN,
			LINKTYPE_X2E_SERIAL,
			LINKTYPE_X2E_XORAYA,
			LINKTYPE_IEEE802_15_4_NONASK_PHY,
			LINKTYPE_LINUX_EVDEV,
			LINKTYPE_GSMTAP_UM,
			LINKTYPE_GSMTAP_ABIS,
			LINKTYPE_MPLS,
			LINKTYPE_USB_LINUX_MMAPPED,
			LINKTYPE_DECT,
			LINKTYPE_AOS,
			LINKTYPE_WIHART,
			LINKTYPE_FC_2,
			LINKTYPE_FC_2_WITH_FRAME_DELIMS,
			LINKTYPE_IPNET,
			LINKTYPE_CAN_SOCKETCAN,
			LINKTYPE_IPV4,
			LINKTYPE_IPV6,
			LINKTYPE_IEEE802_15_4_NOFCS,
			LINKTYPE_DBUS,
			LINKTYPE_JUNIPER_VS,
			LINKTYPE_JUNIPER_SRX_E2E,
			LINKTYPE_JUNIPER_FIBRECHANNEL,
			LINKTYPE_DVB_CI,
			LINKTYPE_MUX27010,
			LINKTYPE_STANAG_5066_D_PDU,
			LINKTYPE_JUNIPER_ATM_CEMIC,
			LINKTYPE_NFLOG,
			LINKTYPE_NETANALYZER,
			LINKTYPE_NETANALYZER_TRANSPARENT,
			LINKTYPE_IPOIB,
			LINKTYPE_MPEG_2_TS,
			LINKTYPE_NG40,
			LINKTYPE_NFC_LLCP,
			LINKTYPE_PFSYNC,
			LINKTYPE_INFINIBAND,
			LINKTYPE_SCTP,
			LINKTYPE_USBPCAP,
			LINKTYPE_RTAC_SERIAL,
			LINKTYPE_BLUETOOTH_LE_LL,
			LINKTYPE_WIRESHARK_UPPER_PDU,
			LINKTYPE_NETLINK,
			LINKTYPE_BLUETOOTH_LINUX_MONITOR,
			LINKTYPE_BLUETOOTH_BREDR_BB,
			LINKTYPE_BLUETOOTH_LE_LL_WITH_PHDR,
			LINKTYPE_PROFIBUS_DL,
			LINKTYPE_PKTAP,
			LINKTYPE_EPON,
			LINKTYPE_IPMI_HPM_2,
			LINKTYPE_ZWAVE_R1_R2,
			LINKTYPE_ZWAVE_R3,
			LINKTYPE_WATTSTOPPER_DLM,
			LINKTYPE_ISO_14443,
			LINKTYPE_RDS,
			LINKTYPE_USB_DARWIN,
			LINKTYPE_OPENFLOW,
			LINKTYPE_SDLC,
			LINKTYPE_TI_LLN_SNIFFER,
			LINKTYPE_LORATAP,
			LINKTYPE_VSOCK,
			LINKTYPE_NORDIC_BLE,
			LINKTYPE_DOCSIS31_XRA31,
			LINKTYPE_ETHERNET_MPACKET,
			LINKTYPE_DISPLAYPORT_AUX,
			LINKTYPE_LINUX_SLL2,
			LINKTYPE_SERCOS_MONITOR,
			LINKTYPE_OPENVIZSLA,
			LINKTYPE_EBHSCR,
			LINKTYPE_VPP_DISPATCH,
			LINKTYPE_DSA_TAG_BRCM,
			LINKTYPE_DSA_TAG_BRCM_PREPEND,
			LINKTYPE_IEEE802_15_4_TAP,
			LINKTYPE_DSA_TAG_DSA,
			LINKTYPE_DSA_TAG_EDSA,
			LINKTYPE_ELEE,
			LINKTYPE_Z_WAVE_SERIAL,
			LINKTYPE_USB_2_0,
			LINKTYPE_ATSC_ALP,
			LINKTYPE_ETW,
			LINKTYPE_NETANALYZER_NG,
			LINKTYPE_ZBOSS_NCP,
			LINKTYPE_USB_2_0_LOW_SPEED,
			LINKTYPE_USB_2_0_FULL_SPEED,
			LINKTYPE_USB_2_0_HIGH_SPEED,
			LINKTYPE_AUERSWALD_LOG,
			LINKTYPE_ZWAVE_TAP,
			LINKTYPE_SILABS_DEBUG_CHANNEL,
			LINKTYPE_FIRA_UCI,
			LINKTYPE_MDB
		};

	}
}

#endif /* LIB_WAYNEPCAP_WAYNEENUMS_HPP_ */
